import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [num,setNum]=useState(0)
  const handleIncrement = () => {
    setNum(num+1)
  }
  const handleDecrement = () => {
    setNum(num-1)

  }
  return (
    <>
      <Head>
        <title>Create React App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <main className={styles.main}>
      <h1>Counter App</h1>
      <div className={styles.inlineClass}> 
        <button className={styles.fontLarge} onClick={handleIncrement}>+</button>
        <div className={styles.fontLarge}>{num}</div>
        <button className={styles.fontLarge} onClick={handleDecrement}>-</button>
      </div>
      </main> 
    </>
  )
}
